### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by pnmcosta**
Please note this PR includes all the changes on https://github.com/async-labs/saas/pull/29 as well, so you can accept only this one if you're ok with the other one.

More info about the docker integration here: https://github.com/pnmcosta/saas-boilerplate/wiki/Changes-on-docker-support-branch but the readme as also been updated.

### CODE REVIEW

**Comment by tima101** [comment]
@pnmcosta I tested tests and starting `app` with a new way of passing env vars - works properly.

Haven't tested Docker but will merge anyway, will test after merging.

Thanks for making a lot of improvements, I think they are all great.

**Comment by pnmcosta** [comment]
awesome, glad I could help and learn at the same time :)

I've got a microsoft graph oauth implementation on the `oauth-azure` (named it wrong!) but it does change the mongo database schema for users, as it now encrypts the tokens using https://github.com/wheresvic/mongoose-field-encryption so it maybe a breaking change to those that already use the boilerplate.

I'll write up some more details on the wiki, and if you'd like I can also PR it.

**Comment by tima101** [comment]
@pnmcosta We already have two ways to authenticate. I suggest just keeping current two: `google oauth` and `passwordless`.

**Comment by pnmcosta** [comment]
Yup, got it, I'll keep the branch cause I'll need it for something i'm working on.

**Pull request merged**
